### ISSUE TITLE
Can't get hanzi and pinyin colored with old cards

### ISSUE THREAD

**Issue by colibris79** [luoliyan/chinese-support-redux#106]
First of all thank you very much for taking your time to design such a useful addon for Anki users/Chinese learners : )

**Describe the bug**
I have my old Chinese deck created with Pinyin Toolkit (that's one of the reasons why I still use Anki 2.0). When I create new cards based on your templates I got all the colors right in both hanzi and pinyin but when I try to modify my old deck cards (that they already have their hanzi and pinyin colored with Pinyin Toolkit) I get everything with letters in black. 
The fields my cards have are: Hanzi, Meaning, pronunciacion, Color, Pinyin, explicacion. I have tried changing the name of the fields and the order to fit the one in the template or the one in the Ankiweb but I always get the Color and Pinyin fields with black letters. Is there any way to edit these old cards and get colored fields?

**Specs (please complete the following information):**
 - OS:Mint 19 (Ubuntu 18.04)
 - Anki Version2.1.15 (442df9d6) Qt 5.12.1 PyQt 5.11.3
- Chinese Support Version 0.11.5

**Comment by joeminicucci** [comment]
Did you try replicating the fields that are listed in the config.json file?

**Comment by colibris79** [comment]
Yes, I've tried using the same names and in the same order but I still can't get them colored

**Comment by colibris79** [comment]
This is what I get
![Screenshot at 2019-12-08 09-03-24](https://user-images.githubusercontent.com/6926441/70382634-166b2500-199a-11ea-8a5f-88c83c22361f.png)

**Comment by bavogit** [comment]
I seem to be running into the same bug.

**Comment by luoliyan** [comment]
I'll be pushing an update to AnkiWeb later today. Let me know if this bug remains.

**Comment by bavogit** [comment]
I just found out that the coloring actually **is working**. I tried applying different colours to the tones using CSS which made the colours visible while reviewing. So this bug is purely visible; the colours will not appear in the editor or in the card reviewer without applying colours through css.

.tone1 {color: #ff6ac1;} 
.tone2 {color: #5af78e;} 
.tone3 {color: #ff9e42;} 
.tone4 {color: #ff5c57;}
.tone5 {color: #d8dad4;}

**Comment by luoliyan** [comment]
I really should mention this in the documentation.

**Comment by colibris79** [comment]
@luoliyan , I have tried last update but unfortunately it didn't solve the problem for me. I still get all fields in black instead of colored. 
@bavogit , that colors the pinyin tones (pronunciation field) but not the hanzi characters. Any way to color them with css code as well?

**Comment by luoliyan** [comment]
@colibris79 Can you post the HTML of those fields here? (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>X</kbd> should bring up the HTML editor) I'm guessing the characters are not marked up in the first place, which means the CSS will never apply.

**Comment by colibris79** [comment]
Here it goes. I send you the HTML original and after applying the addon.
The 'Color' field:
Original:
`
<span style="color:#ff0000">工</span><span style="color:#0000ff">会</span><span style="color:#0000ff">运</span><span style="color:#0000ff">动</span><span style="color:#00aa00">旨</span><span style="color:#0000ff">在</span><span style="color:#ff0000">争</span><span style="color:#00aa00">取</span><span style="color:#0000ff">更</span><span style="color:#ff0000">高</span><span style="color:#545454">的</span><span style="color:#ff0000">工</span><span style="color:#ff0000">资</span><span style="color:#ffaa00">和</span><span style="color:#0000ff">更</span><span style="color:#00aa00">好</span><span style="color:#545454">的</span><span style="color:#ff0000">工</span><span style="color:#0000ff">作</span><span style="color:#ffaa00">条</span><span style="color:#0000ff">件</span>。`

After addon:
`<span class="tone1">工</span><span class="tone4">会</span><span class="tone4">运</span><span class="tone4">动</span><span class="tone3">旨</span><span class="tone4">在</span><span class="tone1">争</span><span class="tone3">取</span><span class="tone4">更</span><span class="tone1">高</span><span class="tone5">的</span><span class="tone1">工</span><span class="tone1">资</span><span class="tone2">和</span><span class="tone4">更</span><span class="tone3">好</span><span class="tone5">的</span><span class="tone1">工</span><span class="tone4">作</span><span class="tone2">条</span><span class="tone4">件</span>`

....................................................................................
The  "Pinyin" field:
Original
`<span style="color:#ff0000">gōng</span> <span style="color:#0000ff">huì</span> <span style="color:#0000ff">yùn</span> <span style="color:#0000ff">dòng</span> <span style="color:#00aa00">zhǐ</span> <span style="color:#0000ff">zài</span> <span style="color:#ff0000">zhēng</span> <span style="color:#00aa00">qǔ</span> <span style="color:#0000ff">gèng</span> <span style="color:#ff0000">gāo</span> <span style="color:#545454">de</span> <span style="color:#ff0000">gōng</span> <span style="color:#ff0000">zī</span> <span style="color:#ffaa00">hé</span> <span style="color:#0000ff">gèng</span> <span style="color:#00aa00">hǎo</span> <span style="color:#545454">de</span> <span style="color:#ff0000">gōng</span> <span style="color:#0000ff">zuò</span> <span style="color:#ffaa00">tiáo</span> <span style="color:#0000ff">jiàn</span>.`

After addon:
`<span class="tone1">gōng</span> <span class="tone4">huì</span> <span class="tone4">yùn</span> <span class="tone4">dòng</span> <span class="tone3">zhǐ</span> <span class="tone4">zài</span> <span class="tone1">zhēng</span> <span class="tone3">qǔ</span> <span class="tone4">gèng</span> <span class="tone1">gāo</span> <span class="tone5">de</span> <span class="tone1">gōng</span> <span class="tone1">zī</span> <span class="tone2">hé</span> <span class="tone4">gèng</span> <span class="tone3">hǎo</span> <span class="tone5">de</span> <span class="tone1">gōng</span> <span class="tone4">zuò</span> <span class="tone2">tiáo</span> <span class="tone4">jiàn</span> <span class="tone5">.</span> 
`

Thanks for your help and sorry about all the hassle

**Comment by luoliyan** [comment]
That looks correct to me. Is the CSS in the section of the template that says `Styling (shared between cards)`? Is the colour showing during reviews?

**Comment by colibris79** [comment]
That was it!!!
Your add-on creates the CSS inside of the Styling section but since my cards are already created that CSS wasn't being added to my card. So I manually added this CSS to my old cards and the add-on is working:
```
.card {
 font-family: arial;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}
.card { word-wrap: break-word; }
.win .chinese { font-family: "MS Mincho", "ＭＳ 明朝"; }
.mac .chinese { }
.linux .chinese { font-family: "Kochi Mincho", "東風明朝"; }
.mobile .chinese { font-family: "Hiragino Mincho ProN"; }
.chinese { font-size: 30px;}
.reading { font-size: 16px;}
.comment {font-size: 15px; color:grey;}
.tags {color:gray;text-align:right;font-size:10pt;}
.note {color:gray;font-size:12pt;margin-top:20pt;}
.hint {font-size:12pt;}
.answer { background-color:bisque; border:dotted;border-width:1px}

.tone1 {color: red;}
.tone2 {color: orange;}
.tone3 {color: green;}
.tone4 {color: blue;}
.tone5 {color: gray;}
```

Thanks! sorry I hadn't realized about it before

**Comment by colibris79** [comment]
I've just realized about something else. If in the field "Hanzi" there is any space between characters, the resulting "Pinyin" field will have all the pinyin linked together, only separated by that space from the Hanzi field. 
Just to let you know in case you see many pinyin together in any of your cards, it may be because there are spaces between characters in the Hanzi field
Great work! it works like a charm and now I can finally migrate to Anki 2.1    : )

**Comment by luoliyan** [comment]
Yeah, the spacing is one of the more complicated issues. For the time being, it just is how it is. There'll be some menu options in the future.
