### ISSUE TITLE
Google TTS doesn't produce proper sound files anymore

### ISSUE THREAD

**Issue by 3ter** [luoliyan/chinese-support-redux#11]
Hi luoliyan,

### Synopsis
Google TTS doesn't seem to produce proper sound files anymore on Anki version 2.1.5. Baidu TTS is producing sound.

### Steps to reproduce
- Use Anki version 2.1.5 ([latest](https://apps.ankiweb.net/))
- Use either the old version of this addon 839350950 (no longer available) or the one for Anki 2.1 [1128979221](https://ankiweb.net/shared/info/1128979221)
  - Use either Google TTS as speech engine
- Create a note and make sure the sound field gets populated
  - I thought this was formerly achieved by tabbing, now I had to click on the first, then a second field
- Save and preview the note

### Observed behavior
- There is no sound to be heard
  - The sound file in the media folder is also not playable (e.g. with VLC)

### Expected behavior
- Google TTS has been producing sound files
  - And the sound was added by pressing _tab_ and not only by clicking

Regards,
3ter

**Comment by luoliyan** [comment]
Thanks. This should be fixed now. Google no longer accept `zh` as a language code, because they now provide `zh-cn` and `zh-tw`. I'll make that an option in the menu at some point, but for now it will default to `zh-cn`.

**Comment by luoliyan** [comment]
I've uploaded the new version to AnkiWeb. Can you confirm that it's working for you now?

**Comment by 3ter** [comment]
Hi luoliyan,

actually I first couldn't update the addon. I've got this debug info from Anki:
Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\addons.py", line 394, in onCheckForUpdates
  File "aqt\addons.py", line 156, in downloadIds
  File "aqt\addons.py", line 117, in install
  File "aqt\addons.py", line 140, in deleteAddon
  File "site-packages\send2trash\plat_win.py", line 58, in send2trash
<class 'OSError'>: Couldn't perform operation. Error code: 124

Then I deleted it from Anki after restarting it with SHIFT held.

After adding it Anki couldn't load but showed:
![image](https://user-images.githubusercontent.com/11499929/46678689-76730980-cbe5-11e8-8733-5038007f8143.png)

**Comment by infernalis** [comment]
I ran into the same issue and, as a hack, removing lines 7 and 8 from that tts.py file seemed to make it work.

**Comment by 3ter** [comment]
> I ran into the same issue and, as a hack, removing lines 7 and 8 from that tts.py file seemed to make it work.

I can't confirm this. Removing those two import statements make the addon load but still I only get sound with Baidu's TTS engine.
