### ISSUE TITLE
Error (addon failed to load) on each startup

### ISSUE THREAD

**Issue by aNerdgirl** [luoliyan/chinese-support-redux#114]
**Describe the bug**
Everytime I start Anki the addon failes to load. The problems occurs witht he newest beta build, but also with the previous one! I use Anki for Windows 10. Tried to reinstall the Addon, but the error keeps occuring!

**To Reproduce**
Start Anki.

**Expected behavior**

**Screenshots**
![error](https://user-images.githubusercontent.com/41619287/72662216-d9f10700-39e4-11ea-9e71-91120a1a807c.png)
![anki version](https://user-images.githubusercontent.com/41619287/72662217-da899d80-39e4-11ea-89c1-5c7aa929f95e.png)

 - Anki Version: 2.1.20beta1, but also 2.1.17beta8, 2.1.17beta7 (Windows 10)
- Chinese Support Redux v0.13.0

Thanks for all the work effort you put into the addon!

**Comment by khonkhortisan** [comment]
[info] https://anki.tenderapp.com/discussions/beta-testing/1708-anki-2120-beta

**Comment by khonkhortisan** [comment]
This was fixed in the Korean fork https://github.com/scottgigante/korean-support/issues/3 https://github.com/scottgigante/korean-support/commit/032e961497bb97587740f60c8177f10fbfa3b8d7

**Comment by luoliyan** [comment]
This should be fixed with the next update.
