### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by icantthinkofa-username** [luoliyan/chinese-support-redux#12]
<img width="400" alt="screen shot 2018-10-09 at 11 31 29" src="https://user-images.githubusercontent.com/43998806/46680856-000be280-cbb8-11e8-8fbb-44ff35f3bdf7.png">

Hi, I installed the addon today and got this message. I'm not sure if it's a problem with my computer or something off with the addon itself. Please let me know if anything else is needed. Thanks!

**Comment by 3ter** [comment]
Hi there,

as @infernalis pointed out [here](https://github.com/luoliyan/chinese-support-redux/issues/11) this is an error in the addon. You can fix it by manually removing lines 7 and 8 in tts.py in the path specified in the error message.

**Comment by luoliyan** [comment]
Thanks folks.

The good news is that Google TTS definitely works. The bad news is I installed the `six` dependency in my virtual environment when I was playing around on the command line, so I didn't notice it wasn't bundled with the add-on.

Give me half an hour.

**Comment by luoliyan** [comment]
It's fixed now. But I just discovered that Google have remove Cantonese TTS, so that had to be dropped from the menu.
