### ISSUE TITLE
Urllib3 dependency in tts.py

### ISSUE THREAD

**Issue by 3ter** [luoliyan/chinese-support-redux#13]
Hi luoliyan,

there's still another dependency error for me which results in failing to load the addon correctly.

It's line 8 in tts.py:
`import urllib3`

The same type of error as in #12:
`ModuleNotFoundError: No module named 'urllib3'`

**Comment by luoliyan** [comment]
Hmmm, are you sure? `urllib3` is a dependency of `requests` which is bundled with Anki. Are you on Windows? Can you do this for me:

1. Open Anki with addons disabled (hold down `Shift` while it's starting)
2. Open the console (`Ctrl+Shift+;`)
3. Paste this in the top box :
```python
for top in sorted(set([m.split('.')[0] for m in modules])):
    print(top)
```
4. Press `Ctrl+Enter`
4. Post the list of modules here for me

**Comment by 3ter** [comment]
>>> for top in sorted(set([m.split('.')[0] for m in modules])):
...     print(top)
Traceback (most recent call last):
  File "aqt\main.py", line 1174, in onDebugRet
  File "<string>", line 1, in <module>
NameError: name 'modules' is not defined

**Comment by luoliyan** [comment]
Sorry, I'm having a sloppy day. It needs to be:

```python
from sys import modules
for top in sorted(set([m.split('.')[0] for m in modules])):
    print(top)
```

**Comment by 3ter** [comment]
```
PyQt5
__future__
__main__
_ast
_bisect
_blake2
_bootlocale
_bz2
_codecs
_collections
_collections_abc
_compat_pickle
_compression
_ctypes
_datetime
_elementtree
_frozen_importlib
_frozen_importlib_external
_functools
_hashlib
_heapq
_imp
_io
_json
_locale
_lzma
_markupbase
_opcode
_operator
_pickle
_portaudio
_random
_sha3
_signal
_socket
_sqlite3
_sre
_ssl
_stat
_string
_struct
_thread
_warnings
_weakref
_weakrefset
_winapi
abc
anki
aqt
argparse
ast
atexit
audioop
base64
binascii
bisect
bs4
builtins
bz2
calendar
cgi
chunk
codecs
collections
contextlib
copy
copyreg
ctypes
datetime
decorator
difflib
dis
distutils
email
encodings
enum
errno
faulthandler
fnmatch
functools
gc
genericpath
getpass
gettext
gzip
hashlib
heapq
hmac
html
http
imp
importlib
inspect
io
ipaddress
itertools
json
keyword
linecache
locale
logging
lzma
markdown
marshal
math
mimetypes
msvcrt
netrc
nt
ntpath
nturl2path
opcode
operator
optparse
os
pickle
platform
posixpath
pprint
pyaudio
pyexpat
pyimod01_os_path
pyimod02_archive
pyimod03_importers
pythoncom
pywintypes
queue
quopri
random
re
reprlib
requests
select
selectors
send2trash
shlex
shutil
signal
sip
socket
socketserver
sqlite3
sre_compile
sre_constants
sre_parse
ssl
stat
string
stringprep
struct
subprocess
sys
tempfile
textwrap
threading
time
token
tokenize
traceback
types
unicodedata
urllib
uu
uuid
warnings
wave
weakref
win32api
win32com
win32file
win32pipe
winerror
winreg
xml
zipfile
zipimport
zlib
```

**Comment by luoliyan** [comment]
Okay, I'm just going to bundle everything.

**Comment by 3ter** [comment]
> Okay, I'm just going to bundle everything.

Is bundling as easy as changing the import statements as described [here on reddit](https://www.reddit.com/r/Anki/comments/6hprgb/how_do_i_bundle_modules_for_add_ons/)?

**Comment by luoliyan** [comment]
That will only work if you have the modules installed on your system. Bundling just means I'll package them up with the add-on so there's no outside dependency.

**Comment by luoliyan** [comment]
Are you able to give the update a try? Download https://ufile.io/b89ef and drop the `chinese` folder into your `addons21`folder.

**Comment by 3ter** [comment]
I'm getting the same error.
![image](https://user-images.githubusercontent.com/11499929/46755356-25d2dd80-ccc5-11e8-9111-13a79788e275.png)

![image](https://user-images.githubusercontent.com/11499929/46755331-16539480-ccc5-11e8-8f6a-336835a3ebed.png)

**Comment by 3ter** [comment]
@luoliyan Shouldn't there be a file called urllib3.py in the folder? I couldn't find one. In the six module folder we have a file six.py as well and this can be imported.
![image](https://user-images.githubusercontent.com/11499929/46759699-510efa00-ccd0-11e8-9418-7db3a249c0c5.png)

**Comment by luoliyan** [comment]
Thanks for your help with this one. The updated `__init__.py` got lost in a different branch. I've tested on Windows. It should work now.

**Comment by 3ter** [comment]
Just wanted to leave another "Thank you!" here 😄.
