### ISSUE TITLE
Incorrect handling of sentences with punctuation

### ISSUE THREAD

**Issue by luoliyan** [luoliyan/chinese-support-redux#14]
Original report: https://github.com/ttempe/chinese-support-addon/issues/71

Commas seem to be handled correctly now, unlike in older version. But several issues remain:

1. If 没有，是我第一次来上海旅游。  is entered in the Hanzi field, the full stop is missing in the color field output.
2. If the input is 没有。没有。 then the output is 没有。没

If anyone has other examples, please post them here.

**Comment by 3ter** [comment]
### Another example (actually I've got a lot 😢)
* Reproduce by entering 今天的网太慢了，老卡。and then TAB.
![image](https://user-images.githubusercontent.com/11499929/49338038-4fe9b180-f61d-11e8-96d6-2194dc7fa232.png)
The sound file is perfect, though.

**Comment by luoliyan** [comment]
Thanks. I'll have a fix for this in the next few days.

**Comment by luoliyan** [comment]
This is fixed in the development code. Expect an update on AnkiWeb soon.

Thanks.
