### ISSUE TITLE
Updated to Anki 2.1.33: error message

### ISSUE THREAD

**Issue by Jeffery25** [luoliyan/chinese-support-redux#151]
After updating to Anki 2.1.33, there were two problems:

1) The "Meaning" field stopped autofilling. I fixed the issue locally by renaming it to "English"

2) An error message pops up every time the add-on tries to autofill (it seems to be autofilling correctly, but I have not extensively tested this). Here are the log errors the message prints:

Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.5
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-04 00:57:41
Add-ons possibly involved: ⁨Chinese Support Redux v0140, Syntax Highlighting for Code⁩

--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 1084, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u6211' in position 96: ordinal not in range(128)

--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 1084, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u6211' in position 181: ordinal not in range(128)

--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 1084, in emit
UnicodeEncodeError: 'ascii' codec can't encode character '\u6211' in position 139: ordinal not in range(128)

**Comment by mollyci** [comment]
I am having exactly the same issue. It's a real shame as this was a big part of my study routine.

**Comment by joeminicucci** [comment]
@Jeffery25 @mollyci Are you still experiencing the same issues in the most recent version?

**Comment by Jeffery25** [comment]
Hi @joeminicucci, apologies for the delayed response. I just re-tested, and it seems to work great for me!
