### ISSUE TITLE
After tab, nothing happens

### ISSUE THREAD

**Issue by HappyRay** [luoliyan/chinese-support-redux#152]
Thanks for making and sharing this tool!
I tried it on my Mac and couldn't get it to work. I am new to anki extensions. It's possible that I missed something. 

I followed the instruction at
https://ankiweb.net/shared/info/1128979221

The step I don't understand is
"Enable Chinese Support Redux for this note type (click 汉字)"
How do I do that? I looked everywhere and still can't figure it out.

**To Reproduce**
My setup:
anki mac version 
Version 2.1.33 (3f403040)
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

Chinese Support Redux v0.14.0
29.11MB. Updated 2020-06-01. Only supports Anki 2.1.x.

Followed the instruction except the step mentioned above.
create a new deck
add a note, select either the Chinese (advanced) or Chinese (basic) as the node type
Enter a word (e.g., 電話) into the Hanzi field 
Press Tab
nothing happens.

**Comment by p2635** [comment]
You should have an icon like the top right, do you see it? 
![image](https://user-images.githubusercontent.com/4522927/93639010-3bdc9300-f9f0-11ea-8494-1748769b1d05.png)

**Comment by HappyRay** [comment]
I see. It worked for me now. Thanks!
