### ISSUE TITLE
Setup for simplified, traditional, or both classifier

### ISSUE THREAD

**Issue by gdelmee** [luoliyan/chinese-support-redux#155]
When entering hanzi, the plugin will fill the available fields.
If I don't set any traditional field, I won't get those. But I will get both simplified and traditional classifiers.

It would be great to have a setup to choose which classifier we'd like to have.

**Comment by joeminicucci** [comment]
Closing as traditional is already supported in recent release, and is also a feature enhancement with insufficient information.
