### ISSUE TITLE
Who is maintaining this project?

### ISSUE THREAD

**Issue by joeminicucci** [luoliyan/chinese-support-redux#174]
There is a backlog of PRs unfulfilled, who has contributor access to the repo, and is still active? It would look to be that the original contributors are now inactive.

**Comment by ahj10** [comment]
I'm willing to support the project if you post a patreon link or gofundme. I suppose financial support could help accelerate improvements and updates on this very important toolbox.

**Comment by joeminicucci** [comment]
Id be fine maintaining it for free, as I have in my PRs, but until someone merges those changes this repo is technically inactive.

**Comment by gpshearn** [comment]
I'd literally pay monthly for this to work. It's a hugely important part of my studying workflow and very aggravating when it gets bugs :(

**Comment by dahmc** [comment]
Yes, maybe we should agree on a fork an take it from there, with more than one maintainer

**Comment by 3ter** [comment]
I'd propose @joeminicucci's fork [here](https://github.com/joeminicucci/chinese-support-redux). He already started he'd be willing and he has been the only one speaking up here since a month.

**Comment by psii** [comment]
I'd be willing to contribute to a fork, provided that its main focus is on stability and bug-fixing.

**Comment by joeminicucci** [comment]
Sure if you all open a PR on my fork, I can assist

**Comment by joeminicucci** [comment]
If that is the route we are going to take, I will need to open a new Anki Add-On page to try and drive bug reports to the new repo rather than to here. Let me know what you all think.

**Comment by 3ter** [comment]
I was thinking along the very same lines. This add-on is still shining in [the list of add-ons](https://ankiweb.net/shared/addons/) so I deem it worthy to keep it in a good working condition (in particular as it focusses on the freely available TTS).

By the way: I just thought to mention @luoliyan here, if he per chance just overlooked us debating this change.

**Comment by dahmc** [comment]
Great idea!

**Comment by joeminicucci** [comment]
Im going to give the original maintainers another couple of weeks to respond before I make a move.

**Comment by luoliyan** [comment]
As I'm sure you can all understand, real life takes priority sometimes. I lost access to my workstation until recently and haven't had time to really follow any of the developments here. My apologies.

Right now I'm probably in a position where I can start coding again on a semiregular basis, but based on the number of people affected by my absence, I'm willing to grant commit access to a few people so there is more consistent maintenance.

I'll chip away at the pull requests over the next couple days and address anything that prevents the add-on from running. In the mean time, anyone who would like commit access to the repo can apply for it here and I'll consider it.

If anyone is willing to help me prioritise the issues, that would also be appreciated. Let me know below what I need to look at first.

**Comment by psii** [comment]
The update to gTTS 2.2.2 is the most pressing matter #161. The plugin is not useable otherwise. Be aware that some of the pull requests here may be still on gTTS 2.2.1, which also stopped working recently.

**Comment by joeminicucci** [comment]
@psii @luoliyan I upgraded locally from gtts 2.2.1 to 2.2.2 and still receive issues on the latest release, which I am trying to work out https://github.com/pndurette/gTTS/issues/252

**Comment by joeminicucci** [comment]
@luoliyan I would like commit privileges, if possible.

**Comment by luoliyan** [comment]
@joeminicucci I've sent a collaborator invite, which on a casual reading of the docs should grant commit access.

I should have my dev environment restored in the next day or so, but don't feel like you have to wait for me. Just use your best judgement and we'll take it from there.

To be honest, my day job is medicine, not programming, so it's an open question whether I remember how to do any of this. (Even trying to set up `pipenv` properly took an embarrassingly long time.)

**Comment by joeminicucci** [comment]
Thanks @luoliyan, I received the invitation and am closing this issue.

**Comment by psii** [comment]
@luoliyan, @joeminicucci, can you give an update on  the current state of this project? It was announced that active development resumes on February 27th. However, I submitted a pull request a week ago with no response so far.

**Comment by joeminicucci** [comment]
@psii I am not actively maintaining the project currently due to life circumstances, but I could take a look at my earliest convenience. The massive backlog of PRs was existent long before I chimed in and those need to be addressed before anything.
