### ISSUE TITLE
Crash after Bulk-Fill

### ISSUE THREAD

**Issue by kangdali** [luoliyan/chinese-support-redux#178]
Hello community,
the bug I recently got occurs when I use bulkfill with the chinese redux addon. When I hit "Tab" it will not fill my empty spaces and after approx. 1 minute the program changes into "no response" mode before I can choose to close it. What could maybe be of interest, is that when I reopen Anki, I can then "Add" a new deck and bulkfill in all the terms, I already filled in before it crashed. SO it goes like: fill word #1 --> crash --> restart Anki and add new deck --> fill word #1 (no problem) --> fill word #2 --> crash --> restart Anki and add new deck --> fill #1 and #2 (no problem) --> fill word #3 --> crash .... and so on.

Since the addon crashes a lot I've already implemented some solutions. I used the #169 bugfix (The gTTS project just released a new version `2.2.1` that fixes the google translation. Copying the new gTTS code over the one shipped in this Anki extension solved it for me. Here are the steps:) 

My Specs are:

Windows 10
Anki 2.1.x 
Chinese Support Redux v0.14.0

I would be super grateful for any type of help, since exams are coming closer and I really need this addon to work.

Best wishes

**Comment by psii** [comment]
Apparently, the #169 fix just recently stopped working because Google changed its service again. [I found a way to mitigate this](https://github.com/luoliyan/chinese-support-redux/issues/169#issuecomment-769820916), I hope it works for you.

**Comment by kangdali** [comment]
I followed your steps and it worked. Thank you very much for your help. 
Have a great day!

**Comment by beTween1** [comment]
Hello, unfortunately, there seemed to be an update.
I followed your steps a few days ago and all was fine, until today, I deleted the files and tried it again, but nothing worked.

Is there a way to fix that issue?
Thank you for your help so far.

Best wishes.

**Comment by psii** [comment]
@beTween1, by update do you mean Anki itself? Or the Addon?

**Comment by beTween1** [comment]
@psii, I reinstalled the addon and followed your steps and it was working again.
Thanks for the help. :)

**Comment by luoliyan** [comment]
I have this working now. I'll upload a new version later today.
