### ISSUE TITLE
Anki 2.1.41 broke chinese support

### ISSUE THREAD

**Issue by dahmc** [luoliyan/chinese-support-redux#180]
**Describe the bug**
After updating to the latest version of Anki (2.1.41), chinese support is not working.
Pressing tab on any field has no effect anymore

**To Reproduce**
Update to Anki 2.1.41

**Expected behavior**
Chinese support still works

**Specs (please complete the following information):**
 - OS: macOS 11.2.1
 - Anki Version 2.1.41
- Chinese Support Version latest

**Additional context**
Workaround is to to go `Switch profile`, then click `Downgrade and Quit`.
Afterwards start Anki 2.1.40 and it works again

**Comment by luoliyan** [comment]
I have a fix for this locally. Expect an updated version on AnkiWeb later today.

Thanks for your patience.

**Comment by dahmc** [comment]
@luoliyan Thanks for looking into this. However, it's not fully working yet, see https://github.com/luoliyan/chinese-support-redux/issues/183

**Comment by luoliyan** [comment]
My bad - was mixing in some pull requests and clobbered my own work. Try version 0.14.2.

**Comment by karl-an** [comment]
As @dahmc mentions #183, I wanted to add that I updated once again but the only reliable text to speech engine is Baidu (although it sounds very artificial to me as compared to google...)

**Comment by dahmc** [comment]
@luoliyan Just tried it, and as @karl-an mentioned, still the same issue. Google doesn't download sounds

**Comment by luoliyan** [comment]
I'm not sure what's going on. I tested it repeatedly with v0.14.2 and got Google audio reliability. It didn't play immediately as the card was added (which I believe was the original behaviour), but it does play during reviews.

I v0.14.1 was a botched fix, which prevented the reported crashes but generated zero byte mp3s instead.

Could everyone make sure they are running 0.14.2 not 0.14.1 and confirm whether that works. It works for me locally, so if it doesn't for you, then I must have packaged the add-on incorrectly.

**Comment by luoliyan** [comment]
I've had a lot of trouble getting `zsh` and `vim` and `pipenv` and the rest of my workflow back to normal, so forgive me if there are some dumb mistakes while I relearn all this stuff.

If you want to try deleting the add-on completely and reinstalling (rather than updating), that might make a difference. I recall there were some persistence issues with stored configuration that I never quite solved.

**Comment by luoliyan** [comment]
We can continue this conversation on #183

I'm just trying to consolidate issues to make life a bit easier.
