### ISSUE TITLE
English field not populating, no color, blank card.

### ISSUE THREAD

**Issue by EddisFargo** [luoliyan/chinese-support-redux#187]
I'm using this app for the first time, so I could be doing something wrong, but it isn't working like the examples. I followed the instructions exactly, I thought. Can anyone find if the error's on my side? 

I literally just downloaded Anki and this extension, and followed the exact steps on Usage for field-filling features.  All settings are default. There are 5 fields. The Hanzi field is where I pasted my characters. The Color field filled out in black and white--looks pretty much exactly the same as the Hanzi field. The pinyin field filled out in black and white. The English field did not fill out at all. The sound field looks good, as far as I know. 

(Note: Please ignore the missing character. I seem to have deleted one before the screenshot--they did absolutely match before and that's not part of my troubles).

![image](https://user-images.githubusercontent.com/79875718/120060649-c8266780-c00d-11eb-9b2d-961ef29b90ff.png)

Then, when I tried to study the deck (well, the one test card I uploaded), the card is blank.  
![image](https://user-images.githubusercontent.com/79875718/120060705-1471a780-c00e-11eb-8275-b3aae6e9c6d7.png)

When I hit "show answer," I see the characters/pinyin in color and hear the audio, all great. But I'm not sure what wa supposed to be on the front of the card.
![image](https://user-images.githubusercontent.com/79875718/120060864-0cfece00-c00f-11eb-835f-3168bfa00c97.png)

 - OS: Windows. 
 - Anki Version 2.1.44
- Chinese Support Version v0.14.2

**Comment by rudyeikichi** [comment]
I think, not sure, that it's because the selected word is actually two words (or at least two words that usually don't come up together in a dictionary as a single word), so it should search two definitions on the online dictionary instead of just one. It has no problems with tones cuz it shows you the first pronunciation it found for each hanzi. If you try with a full sentence it'll do the same.

**Comment by EddisFargo** [comment]
Oh man, I feel so silly it didn't even occur to me it was the specific input! I can't even remember where I pasted it from originally when I was testing it out. I want to say _surely_ I tried other inputs before I gave up, but I'm thinking back to a month ago and I'm.... not sure I did. Basic debugging, 1. Me, 0. 

I just tried it with 中文 and it worked fine. 

It still doesn't show color on the adding bit, but it does show it when I actually try to review the card, so I guess that's all that matters. 

Thank you so much for finding this old question and answering it! Maybe I'll try Anki again now that I've figured out what I did wrong.

**Comment by rudyeikichi** [comment]
### I pasted it from originally when I was testing it out.: 
You probably copied from the title on the cover of a **Chinese crash course** book.

You welcome!

For the colour you should wait help from others (I'm not into coding/programming)
