### ISSUE TITLE
I added type in the answer to the front of the card, now the auto regeneration isn't working

### ISSUE THREAD

**Issue by Blackpantherrx** [luoliyan/chinese-support-redux#189]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]
 - Anki Version [e.g. v2.0.52, v2.1.5]
- Chinese Support Version [e.g. v0.5.3-beta]

**Additional context**

**Comment by joeminicucci** [comment]
Closed for insufficient / non-existent bug details
