### ISSUE TITLE
Fails to Create new Notes

### ISSUE THREAD

**Issue by infernalis** [luoliyan/chinese-support-redux#22]
**Describe the bug**
When creating a new note, the note fails to pass the creation and formatting of fields. This can be solved locally by removing the extra 'True' argument being passed to the 'accentuate' function. This function is called in both format Pinyin and format Pinyin TW.

**To Reproduce**
1. Create a new note with a pinyin field
2. Enter Chinese and click outside the field
3. Observe the crash

**Expected behavior**
Notes should able to be created without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/26908463/48788701-5d1bad80-ecb9-11e8-8684-a3fd839f346b.png)

**Comment by luoliyan** [comment]
Ouch. How did that slip through.

Obviously that should have been passed to `separate` and not `accentuate`. This is why I'll be happy when all the ugly deep nesting of calls is gone.

I'll fix this over the weekend.

**Comment by luoliyan** [comment]
The next version will be uploaded to AnkiWeb soon. Thanks for your patience.
