### ISSUE TITLE
Crash on character "睘"

### ISSUE THREAD

**Issue by telotortium** [luoliyan/chinese-support-redux#23]
Anki crashes whenever Chinese Support Redux attempts to fill in the card for "睘". 

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]: macOS Mojave 10.14.1
 - Anki Version [e.g. v2.0.52, v2.1.5] v2.1.6-test
- Chinese Support Version [e.g. v0.5.3-beta] v0.8.2

**Additional context**
This character seems to have some fields missing in CEDICT, if [MDBG](https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb=%E7%9D%98) is anything to go by.

**Comment by luoliyan** [comment]
There are several characters that cause a crash currently. I've got some fixes in place locally, so expect an update for this over the weekend.

**Comment by telotortium** [comment]
Duplicate of #34
