### ISSUE TITLE
Classifier not filled on partially filled notes

### ISSUE THREAD

**Issue by telotortium** [luoliyan/chinese-support-redux#24]
Drop-down menu "Fill Notes" > "Fill Translation" doesn't populate Mean Word/Classifier fields. I tested it on a deck with definitions already filled in. If I manually press TAB in the "Hanzi" field on such cards that I've previously filled in using that menu, the mean word is filled in.

**Specs (please complete the following information):**
 - OS: [e.g. Windows, iOS, Ubuntu]: macOS Mojave 10.14.1
 - Anki Version [e.g. v2.0.52, v2.1.5] v2.1.6-test
- Chinese Support Version [e.g. v0.5.3-beta] v0.8.2

**Comment by luoliyan** [comment]
I'll see if I can reproduce. I did some testing of that previously (and it worked fine, obviously), but I wouldn't be surprised if I've introduced a regression somewhere.

**Comment by luoliyan** [comment]
This should be fixed. Thanks for your patience.
