### ISSUE TITLE
wrong pinyin

### ISSUE THREAD

**Issue by perokhel92** [luoliyan/chinese-support-redux#26]
**Describe the bug**
While I was adding new note it wrongly produced Pinyin for one common character in each word.

**To Reproduce**
1. Press 'a' to add new note.
2. Press '汉字' button.
3. Type only '开' or a word that contain it.
4. Press Tab.
5. Instead of 'kāi' it will show 'fēng' in all readings I mean Pinyin, Ruby and Bopomofo.

**Expected behavior**
It was expected to input 'kāi' or it's sound in all reading fields.

**Screenshots**
![screen shot 2018-12-09 at 9 40 22 pm](https://user-images.githubusercontent.com/45737350/49700067-9631a880-fbfb-11e8-8286-7b98100067ec.png)
![screen shot 2018-12-09 at 9 41 08 pm](https://user-images.githubusercontent.com/45737350/49700071-9fbb1080-fbfb-11e8-96c3-a0a7ae28e784.png)

**Specs (please complete the following information):**
 - OS: mac OS High Sierra 10.13.6
 - Anki Version 2.1.4
- Chinese Support Version v0.8.4-beta

**Additional context**

**Comment by luoliyan** [comment]
Thanks for the report. This will probably require an overhaul of the database, so it won't be the quickest of all fixes unfortunately.

**Comment by luoliyan** [comment]
While I was fixing other things, I've apparently also fixed this.

Let me know if you find any other examples like this.
