### ISSUE TITLE
Exception filling missing fields

### ISSUE THREAD

**Issue by fultonm** [luoliyan/chinese-support-redux#3]
Mac Version:
10.13.2 (17C205)

Anki 2.1.0beta32 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Mac 10.13.2
Flags: frz=True ao=True        

Caught exception:
  File "/Users/michaelfulton/Library/Application Support/Anki2/addons21/839350950/fill_missing.py", line 267, in fill_simp_trad
    if (has_field(Simplified_fields, note_dict) or has_field(Traditional_fields, note_dict)) and has_field(Hanzi_fields, note_dict):
<class 'NameError'>: name 'Simplified_fields' is not defined

**Comment by fultonm** [comment]
I solved this by hardcoding the field label in the method like this:
```
if (has_field(['Simplified'], note_dict) or has_field(['Traditional'], note_dict)) and has_field(['Hanzi'], note_dict):
            d_has_fields += 1
```
I assume Traditional_fields is initialized some where with the field label in multiple languages or something, but I couldn't find it.

**Comment by luoliyan** [comment]
Thanks. This should be fixed now.
