### ISSUE TITLE
Filling Pinyin throws

### ISSUE THREAD

**Issue by Rentier** [luoliyan/chinese-support-redux#31]
**Describe the bug**
When trying to fill Pinyin, it throws an error and stops. I assume the error is that you have two functions with the same name `fill_pinyin`, one in `behaviour.py`, one in `fill.py`. They are shadowed in `fill.py`.

**To Reproduce**
1. Open a deck
2. Click on `Chinese -> Fill Notes -> Fill Transcription and Color`
3. See error

**Expected behavior**
It fills Pinyin fields.

**Error Message**

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.5 Python 3.6.1 Qt 5.9.2 PyQt 5.9
Platform: Windows 7
Flags: frz=True ao=True sv=1

Caught exception:
  File "E:\AnkiData\addons21\1128979221\fill.py", line 185, in fill_pinyin
    results += fill_pinyin(hanzi, note_dict)
<class 'TypeError'>: fill_pinyin() takes 0 positional arguments but 2 were given
```

**Specs (please complete the following information):**
 - OS: Windows
 - Anki Version: v2.1.5
- Chinese Support Version: v090

**Comment by danielrenninghoff** [comment]
Here's how to fix this until the author fixes it in the official addon. I just post this here because there are probably many chinese learners who don't know the python programming language.

In the Anki Addon Window select "Chinese support redux" and click on View Files. Then open fill.py with a text editor. In line 30 replace
```py
    fill_pinyin,
```
with:
```py
    fill_pinyin as fill_pinyin2,
```

In line 185 replace
```py
                results += fill_pinyin(hanzi, note_dict)
```
with
```py
                results += fill_pinyin2(hanzi, note_dict)
```
Save the file. After restarting Anki the addon should work as expected.

**Comment by jay-pee** [comment]
thanks worked for me :). though it looks like a hack. is there still a fill_pinyin function in use (not the fill_pinyin2 function)? otherwise you could be so kind and make a pull request. :)

**Comment by luoliyan** [comment]
Sorry for the hiccup, folks. This should be fixed in the development code. I'll upload to AnkiWeb tomorrow.

Let me know if I've broken anything else.
