### ISSUE TITLE
彩色 field not autofilling, and existing content erased

### ISSUE THREAD

**Issue by mawis** [luoliyan/chinese-support-redux#35]
When I use the current version (0.9.1) of the plugin to write new notes the field 彩色 doesn't get filled. If I edit an existing note that had this field populated, the content of the field even gets cleared.
I'd expect the field to hold the colored version of the characters I entered.

**Comment by mawis** [comment]
I have no work around for this so far. I just don't write new cards and edit existing cards without this add-on at the moment

**Comment by YuriyTe** [comment]
Yea! I  see. :(
Thanks for your answer.
 I need this add-on, I make new cards. So I do it in old Anki with old version of the Add-on. But it's not very convenient.

**Comment by sdnii** [comment]
This is happening to me too when I am editing cards in the browser, but when I add new cards to the Chinese Advanced deck it works. But it was working in the edit mode until it randomly stopped.

**Comment by luoliyan** [comment]
Thanks. I'll hopefully have this fixed soon.

**Comment by p2635** [comment]
Is it still happening? I can't recreate the problem

**Comment by mawis** [comment]
Yes, still happens here.

Anki 2.1.14
Installed plugins: Chinese Support Redux v0100
Large and Colorful Buttons
Set Font Size
OS: Windows 10/64 Bit

**Comment by mawis** [comment]
Maybe this is related or the same bug: #57

**Comment by luoliyan** [comment]
I can't reproduce this, so I assume it was covered by one of the other bugfixes.
