### ISSUE TITLE
Coloring when changing tone is wrong

### ISSUE THREAD

**Issue by mawis** [luoliyan/chinese-support-redux#36]
**What I do**
* I try to create a new note for 雄伟.
* I see the field 拼音 is populated with _xíongwei_.
* I want to change the tone of the second syllable to _wěi_.
* I add the digit 3 at the end: _xíongwei3_

**What happens**
* Field is updated to _xiongwěi_
* Field is completely colored as tone 3.

**What I would expect**
* Field gets updated to _xióngwěi_
* Tone coloring is 2, 3.

Plugin version: 0.9.1
Anki version: 2.1.4

**Comment by luoliyan** [comment]
Hi Matthias,

Can you let me know if this is fixed for you in the development version (0.10.0)?

**Comment by mawis** [comment]
Yes, seems to work now. Thanks.
