### ISSUE TITLE
Punctuation ruins the quality of Pinyin transcription

### ISSUE THREAD

**Issue by AdrienLE** [luoliyan/chinese-support-redux#41]
**Describe the bug**
I know there is still work being done on improving the transcription, but this is potentially a low hanging fruit: I've noticed that sometimes including a punctuation character makes the transcription a lot more mediocre.

**To Reproduce**
1. Add a card, and write "我要喝湯" as the Hanzi. The transcription will be "wǒyàohētāng", which is correct.
2. Add a card and write "我要喝湯！" (same as before but with an exclamation mark), the transcription will be "wǒ yāo hē tāng ！" (with a first tone on "yao"), which is incorrect, even though it's the exact same sentence except for the exclamation mark at the end, far from the word that is affected.

**Expected behavior**
Punctuation doesn't affect transcription except to the extent that it indicates word separation.

**Specs (please complete the following information):**
OS: Mac Os X
Anki Version 2.1.7
Chinese Support Redux v091

**Comment by luoliyan** [comment]
Thanks. This is fixed in the development code. I've added your example as a test to prevent regression.
