### ISSUE TITLE
Unable to update due to error in send2trash

### ISSUE THREAD

**Issue by onaphta** [luoliyan/chinese-support-redux#46]
**Describe the bug**
Hi, again it is impossible to update the add-on, [just like last time](https://github.com/luoliyan/chinese-support-redux/issues/30).

**To Reproduce**
When I try to update, I get this error:

Anki 2.1.7 (a6c34fd7) Python 3.6.7 Qt 5.12.0 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\addons.py", line 394, in onCheckForUpdates
  File "aqt\addons.py", line 156, in downloadIds
  File "aqt\addons.py", line 117, in install
  File "aqt\addons.py", line 140, in deleteAddon
  File "lib\site-packages\send2trash\plat_win.py", line 86, in send2trash
<class 'OSError'>: [WinError 124] None: 'C:\\Users\\ASUS\\AppData\\Roaming\\Anki2\\addons21\\112897~1'

**Comment by Frudel** [comment]
I just had the "WinError 124" issue in my addon, too. The error message is totally misleading, because it suggests, that the directory may be wrong. The reason however are files, that are in use. So the cause is in your addon, maybe a dictionary or other database file.

**Comment by luoliyan** [comment]
@Frudel Was it the same/similar traceback, involving `onCheckForUpdates`?

**Comment by Frudel** [comment]
> @Frudel Was it the same/similar traceback, involving `onCheckForUpdates`?

Yes, it was in a similar traceback. The culprit is "deleteAddon", which uses send2trash. send2trash then fails, because some files in the addon's directory cannot be deleted. In my case, I had an sqlite database open.
