### ISSUE TITLE
Baidu Speech Engine returning empty files

### ISSUE THREAD

**Issue by fultonm** [luoliyan/chinese-support-redux#5]
I created some new cards yesterday using the same process I've been using for months, but now each of the sound files either does not play or are just 0-second files, or they are silent files. Each generated file, regardless of the length of the sentence are just 132 bytes.

Changing the TTS engine in Anki->Tools->Chinese Support->Set speech egnine->Google TTS works fine but Baidu does produce superior pronunciation.

**Comment by luoliyan** [comment]
Thanks for the report. I'll have a look at this soon.

**Comment by fultonm** [comment]
Baidu TTS is working again as I tried it today. I'll keep you updated if the problem returns. Thank you for this addon :)

**Comment by luoliyan** [comment]
Thanks for the update. I'll be looking at adding more TTS services in the future.
