### ISSUE TITLE
Help a Python beginner

### ISSUE THREAD

**Issue by rjpeterson** [luoliyan/chinese-support-redux#51]
I've been experimenting with the code for this add-on a bit but I'm running into an issue where if I try to run a file in a console that contains a relative import statement (e.g. "from .hanzi import has_hanzi") I get a ModuleNotFoundError.

Anyone able to help me out? I'd love to participate more in the development of this add-on, but this error is making it hard to do any kind of testing.

**Comment by rjpeterson** [comment]
Here is an example of the error:

runfile('D:/My Documents/Code/Python/chinese-support-redux/chinese/transcribe.py', wdir='D:/My Documents/Code/Python/chinese-support-redux/chinese')
Traceback (most recent call last):
  File "D:\My Documents\Code\Python\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b02d91de0ad9>", line 1, in <module>
    runfile('D:/My Documents/Code/Python/chinese-support-redux/chinese/transcribe.py', wdir='D:/My Documents/Code/Python/chinese-support-redux/chinese')
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/My Documents/Code/Python/chinese-support-redux/chinese/transcribe.py", line 22, in <module>
    from .bopomofo import bopomofo
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2018.3.1\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named '__main__.bopomofo'; '__main__' is not a package

**Comment by rjpeterson** [comment]
Maybe a better question is: 
What are the best ways to go about testing changes to the code for add-ons like this? 

I know there has to be a way to test say... the functions inside of the color.py file without having to actually start the Anki GUI.  I've tried many things (running the file in pycharm console, running python from a terminal, manually adding the anki and aqt packages to the add-on's library) but I eventually ran across a "missing win32file module" error and gave up.

**Comment by luoliyan** [comment]
Thanks for your interest.

I'll add some instructions to the readme on how to set up a test environment. I don't have a lot of free time at the moment, but I'll try to get this done in the next couple days.

于 2019年3月14日 GMT+09:30 下午9:34:41, rjpeterson <notifications@github.com> 写到:
>Maybe a better question is: 
>What are the best ways to go about testing changes to the code for
>add-ons like this? 
>
>I know there has to be a way to test say... the functions inside of the
>color.py file without having to actually start the Anki GUI.  I've
>tried many things (running the file in pycharm console, running python
>from a terminal, manually adding the anki and aqt packages to the
>add-on's library) but I eventually ran across a "missing win32file
>module" error and gave up. 
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/luoliyan/chinese-support-redux/issues/51#issuecomment-472824373

-- 
使用 K-9 Mail 发送自我的Android设备。

**Comment by luoliyan** [comment]
I've added some basic instructions to the [readme](https://github.com/luoliyan/chinese-support-redux#testing). I don't really have experience with PyCharm, so I can't tell you how to test it through that IDE. When I program on Windows, I generally set up a basic Unix environment (with [MSYS2](https://www.msys2.org) or something similar) and run everything from the command line.

Let me know if you have any other questions.
