### ISSUE TITLE
Pinyin does not fill in after hitting tab key

### ISSUE THREAD

**Issue by shanghaidavid** [luoliyan/chinese-support-redux#53]
**Describe the bug**
Pinyin does not fill in after hitting tab key

**To Reproduce**
1. open deck
2. enter Hanzi
3. clink tab key
4. pinyin field is empty

**Expected behavior**
Pinyin field should populate

**Screenshots**
See my screenshot
![ankiscreenshot](https://user-images.githubusercontent.com/22862494/54734993-59a02080-4bde-11e9-8a06-ad59a1a26b20.png)

**Specs (please complete the following information):**
 - OS: Windows 10
 - Anki Version: Version 2.1.11 (3cf770c7)
- Chinese Support Version v0.10.0

**Additional context**
Not sure if this is my configuration or a bug but it worked before I upgraded

**Comment by luoliyan** [comment]
It doesn't look like you've enabled the add-on. The `汉字` button should have a black line under it.

**Comment by shanghaidavid** [comment]
1. See attachment. How should I enable it?
2. I have Anki on my Mac too and it has the same problem (sorry I did not add that to the original)
![Capture anki](https://user-images.githubusercontent.com/22862494/55386810-dded8e80-5562-11e9-884c-91b813d2273e.PNG)

**Comment by luoliyan** [comment]
Have you tried clicking it? (https://github.com/luoliyan/chinese-support-redux#usage)

**Comment by shanghaidavid** [comment]
You are correct. Thank you.
I had been using ANKI for 4 years and never noticed this before ..... :(
Great software. Thank you.
