### ISSUE TITLE
Color does not get filled when Pinyin is present

### ISSUE THREAD

**Issue by PandaScience** [luoliyan/chinese-support-redux#57]
**Describe the bug**
FIeld "color" does not get filled when a field with name "pinyin" is present.

**To Reproduce**
1. Add fields with names "color" and "pinyin".
2. Add new note by inserting e.g. 拼音 and press <kbd>TAB</kbd>.
3. Notice that "color" will be empty, wheres "pinyin" and "Pinyin" both get filled.

**Expected behavior**
All fields should be filled regardless which other fields are present.

**Screenshots**
![Missing Color Field](https://user-images.githubusercontent.com/8038521/55685402-0a841a80-5956-11e9-945d-475d8af383fe.png)

**Specs (please complete the following information):**
 - OS: Arch Linux
 - Anki Version 2.1.11 (3cf770c7)
- Chinese Support Version v0.10.0-beta

**Comment by jugurtha6656** [comment]
ya i have a similar error on PC with the same anki and chinese support versions

**Comment by luoliyan** [comment]
As far as I can tell, this works as expected, at least in the current version.
