### ISSUE TITLE
Consistent German, English and French translations

### ISSUE THREAD

**Issue by PandaScience** [luoliyan/chinese-support-redux#59]
**Describe the bug**
Not really a bug, more a convenience issue. I think the translations to all languages should be formatted similarly. Currently, EN and FR seems to use new lines for each synonym, whereas for GER, often all is in one line, divided by colons (see screenshot). Users can then choose a formatting they like via JS scripts. 
This is related somehow to #58.

**Expected behavior**
Divide possible translations by new lines like for EN and FR instead of using colons.

**Possible solution**
A simple `string.replace(", ", "\n")` or in case it's HTML `string.replace(", ", "<br>")` should do it.

**Screenshots**
![Inconsistent German translation string](https://user-images.githubusercontent.com/8038521/55717054-c85fe500-59f8-11e9-9d78-447bb0bb4f6d.png)

**Specs (please complete the following information):**
- OS: Arch Linux
- Anki Version 2.1.11 (3cf770c7)
- Chinese Support Version v0.10.0-beta

**Comment by luoliyan** [comment]
This is fixed, as per #58. Thanks for reporting.
