### ISSUE TITLE
Can't download addon: Error 404

### ISSUE THREAD

**Issue by linguax-gc** [luoliyan/chinese-support-redux#6]
Hi, I cannot download the addon. When entering the code in Anki Desktop I get the error: "Download failed: Error downloading: 404". I tried with other addons and it's working, so it should be a specific problem with this addon.

Also, the addon does not appear on the Ankiweb addon browser (but the page exists, of course, I found it on Google).

**Comment by eiennosihaisya** [comment]
I had the same problem while using Anki v2.0, before realizing this is a port for the Anki v2.1 beta

**Comment by luoliyan** [comment]
Yes @eiennosihaisya, I believe that was the problem.
