### ISSUE TITLE
Addon not working after first add

### ISSUE THREAD

**Issue by PandaScience** [luoliyan/chinese-support-redux#60]
**Describe the bug**
After the first note is added in one "session", for the next one auto-filling does not work anymore, although the addon is still enabled - at least visually via the button.

**To Reproduce**
1. Go to your deck
2. Click on "Add" located in top bar
3. Add new note using this addon (enter hanzi + <kbd>Tab</kbd>)
4. Click "Add" button at bottom --> fields get cleared, note is submitted.
5. Try same thing again --> no auto-filling o.O

Disabling and enabling again the addon via button does not help.

**Expected behavior**
Auto-filling should work when button is enabled.

**Specs (please complete the following information):**
- OS: Arch Linux
- Anki Version 2.1.11 (3cf770c7)
- Chinese Support Version v0.10.0-beta

**Comment by p2635** [comment]
Are you still having this problem?

**Comment by luoliyan** [comment]
Sorry, I tried to replicate this but I don't see the same behaviour.

Update to the latest version and let me know if it's still an issue.

**Comment by PandaScience** [comment]
Sorry for the late reply. I can confirm that this seems not to be an issue anymore.
