### ISSUE TITLE
Addon download https://ankiweb.net/shared/download/1128979221 gives 404 error

### ISSUE THREAD

**Issue by eizanprime** [luoliyan/chinese-support-redux#64]
I am on anki 2.1.11 on archlinux, but this is not relevant because even the download url in a browser doesn't work. 

I have tested a few other addon downloads and they did work.

Is there any workaround to use the addon while the url issue is fixed ? I have always found this addon really great and would like to keep using it.

Thank you very much !

**Comment by luoliyan** [comment]
I think this might've just been a transient issue with AnkiWeb. Seems fine now.
