### ISSUE TITLE
Add frequency field for words

### ISSUE THREAD

**Issue by p2635** [luoliyan/chinese-support-redux#66]
**Is your feature request related to a problem? Please describe.**
I want to know how a Chinese word ranks in terms of frequency and decide whether it is worth learning.

**Describe the solution you'd like**
Generate a number for a 'frequency' field

**Describe alternatives you've considered**
No idea.

**Additional context**
I'm not sure how it works with rights/permissions to use other people's API etc. This is probably the first step, try and find an API or a free frequency dictionary of some sort?

**Comment by p2635** [comment]
I found this but there isn't much info at all so I emailed them: https://usechinese.com/LanguageTools/ZiFrequency

**Comment by p2635** [comment]
I'm new to coding but want to give this a go but I'm stuck already..
1. As wordfreq is a separate library, do I have to download it and all of its dependencies to even begin to start developing this as part of the addon?
2. If someone could talk me through how the logic with filling the note works, hold my hand through this, that would be great.

**Comment by p2635** [comment]
I started it and wrote some methods but I'm still frustrated at my problem 1 above: https://github.com/p2635/chinese-support-redux/tree/wordfreq-support. I don't know how to import the library without copying it into the folder first. Even if I do copy it into the folder, wordfreq itself has dependencies and I have to copy all of them over too???

**Comment by p2635** [comment]
Actually, there's this as well! https://github.com/ernop/anki-chinese-word-frequency

**Comment by p2635** [comment]
Closing this as it's sufficient for my purpose for now.

**Comment by p2635** [comment]
Is the Ankiweb version up to date with the support for frequency?

Maybe I can write up something if there is some sort of changelog for the users to see.

**Comment by luoliyan** [comment]
It's there, yes. I think I also updated the Advanced template to
include it by default.

But this is all on the assumption I haven't completely bricked the add-
on with the latest update.

**Comment by p2635** [comment]
Added a quick note to the readme on  #85
