### ISSUE TITLE
Better sync warning message

### ISSUE THREAD

**Issue by ms4720** [luoliyan/chinese-support-redux#68]
**Describe the bug**

- the sync conflict warning message is opaque, it gives you no information other than there is a problem. if you guess wrong you can lose work.  

- if you click download/sync from the web any new decks that you have created are deleted.   

**To Reproduce**
1. create new deck
2. hit the sync button
3. choose download from the web
4. new deck deleted 

**Expected behavior**
new deck not disappearing on a sync or at least a detailed warning of what would happen 

**Specs (please complete the following information):**
 - OS: OSX high seria 
 - Anki Version: 2.1.13 (3ba55990)
- Chinese Support Version: v0.10.0

**Additional context**

**Comment by p2635** [comment]
Hi, I don't think this problems is related to the Chinese support add on. Please report to Anki directly: https://anki.tenderapp.com/discussions/ankidesktop

**Comment by luoliyan** [comment]
Philip is correct. This add-on doesn't generate any sync warnings; Anki does.
