### ISSUE TITLE
Incorrect tone in Zhuyin for 狭隘

### ISSUE THREAD

**Issue by mawis** [luoliyan/chinese-support-redux#79]
**Describe the bug**
Sometimes the tones are missing in Zhuyin.

**To Reproduce**
1. Create a new card
2. Add 狭隘 to the 汉字 field
3. Press the tab key

**Expected behavior**
I would expect the generated Zhuyin to be ㄒㄧㄚˊ ㄞˋ
but instead the generated Zhuyin is ㄒㄧㄚㄞˋ (see the missing ˊ after the first syllable).

**Screenshots**
![20190802_incorrect_tone](https://user-images.githubusercontent.com/2042030/62377609-6432d500-b543-11e9-995f-1c1e2821be13.png)

**Specs (please complete the following information):**
 - OS: Linux (NixOS 19.03 with xmonad as the window manager)
 - Anki Version 2.1.9
- Chinese Support Version v0100

**Comment by luoliyan** [comment]
Thanks. Should be fixed now.

**Comment by mawis** [comment]
If it should be fixed in v0111 ... it isn't.

**Comment by luoliyan** [comment]
![image](https://user-images.githubusercontent.com/24988028/63031654-7faec000-bef3-11e9-80d6-5610a93e9cfe.png)

**Comment by luoliyan** [comment]
Possibly your field names are not correct. At some point I accidentally committed a work-in-progress `config.json` that changed the list of valid names. Check https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json
