### ISSUE TITLE
Interferes with Japanese Support

### ISSUE THREAD

**Issue by eiennosihaisya** [luoliyan/chinese-support-redux#8]
While using both this and the Japanese Support addon together, Japanese won't auto add readings unless the Chinese Support option is on. And it adds  comment to the reading field, which effects {{kana:Reading}} output. Also attempts to fill Meaning field from Chinese dictionary. This could be fixed by only operating on note types containing the word "Chinese" in its name, as the Japanese Support only operates on note types containing the word "Japanese."

**Comment by luoliyan** [comment]
It only operates on notes it has been enabled for, right? I'm coming back to this add-on after a long break, so I'm a bit fuzzy on the internals at the moment.

If you can give me full steps to reproduce, I'll have a go at fixing it.
