### ISSUE TITLE
Incorrect separation into Pinyin syllables

### ISSUE THREAD

**Issue by mawis** [luoliyan/chinese-support-redux#81]
**Describe the bug**
The word 不言而喻 becomes the syllables bù yá nér yù.

**To Reproduce**
1. Create a new card
2. Enter 不言而喻 in the 汉字 field.
3. Tab through the fields until after the 拼音 field.

**Expected behavior**
“yánér" should be colored in the second tone, instead “nér” is colored in the 4th tone. This problem is similar to #80, but here in addition it gets visible, that the chinese support plugin sees the syllable boundaries incorrectly. Because of that, also the generated Zhuyin is incorrect (ㄅㄨˋ ㄧㄚˊ ㄋㄦ ㄩˋ is generated, but it shoud be ㄅㄨˋ ㄧㄢˊ ㄦˊ ㄩˋ).

**Screenshots**
![20190803_incorrect_boundaries](https://user-images.githubusercontent.com/2042030/62411556-ffd04e00-b5f4-11e9-8f66-31561fff72ad.png)

**Specs**
 - OS: Linux (NixOS 19.03)
 - Anki Version 2.1.9
- Chinese Support Version v0100

**Comment by luoliyan** [comment]
Thanks for all the bug reports. I'll try to reproduce these in the development code.

**Comment by luoliyan** [comment]
This is two bugs, it would seem. The first one (Pinyin colours) is fixed in the development code. The second is incorrect Zhuyin transcription.

**Comment by luoliyan** [comment]
I believe I've fixed the second bug as well.

(As with any of this, there'll be a delay before the development code makes it's way to AnkiWeb.)

**Comment by mawis** [comment]
If it should be fixed in v0111 ... it isn't.
