### ISSUE TITLE
Sound field not autofilling, and exception with transcription bulk filling

### ISSUE THREAD

**Issue by RoslynMGreen** [luoliyan/chinese-support-redux#82]
**Describe the bug**
After a week of working seamlessly, the sound field no longer fills. Thanks for any help you can provide.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to add card - Chinese basic
2. Type in characters and hit tab.
3. No sound is downloaded
4. See copied error message given at bottom of this window.

**Expected behaviour**
I expected to have both the pinyin and the sound download automatically, but this did not occur. 

**Screenshots**

**Specs (please complete the following information):**
- iOS
- Anki Version 2.1.14 (7b93e985)
- Chinese Support Redux v0100

**ERROR MESSAGE**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.1 Qt 5.9.7 PyQt 5.9
Platform: Mac 10.11.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Chinese Support Redux v0100

Caught exception:
  File "/Users/gr/Library/Application Support/Anki2/addons21/1128979221/fill.py", line 185, in bulk_fill_transcript
    'hanzi': get_hanzi(copy),
<class 'UnboundLocalError'>: local variable 'copy' referenced before assignment

**Comment by luoliyan** [comment]
Thanks for letting me know.

I think I broke the bulk filling at some point, and the sound not filling is a separate issue that I hope a library update will fix. I'll see what I can do.

**Comment by RoslynMGreen** [comment]
Thanks very much for getting back to me!

**Comment by mfitzhugh** [comment]
I'm also experiencing this issue. Thanks for your continued work on this plugin. It's a great gift to the Anki community and I know that a lot of folks deeply appreciate it!

**Comment by dennismag** [comment]
Experiencing this as well. Neither meaning nor sound is getting filled anymore.

**Comment by luoliyan** [comment]
The sound field should now be populated when editing a note, but bulk filling appears broken for the time being. I'll try to find some time to take a closer look.

**Comment by RoslynMGreen** [comment]
Thank you very much for doing this for us. I really appreciate it.

**Comment by luoliyan** [comment]
This should be fixed in the upcoming release.
