### ISSUE TITLE
send2trash path error, and missing typing module

### ISSUE THREAD

**Issue by onaphta** [luoliyan/chinese-support-redux#84]
There was a similar problem in the past. I get this error when updating:

Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\addons.py", line 589, in onCheckForUpdates
  File "aqt\addons.py", line 279, in downloadIds
  File "aqt\addons.py", line 201, in install
  File "aqt\addons.py", line 216, in _install
  File "aqt\addons.py", line 234, in deleteAddon
  File "lib\site-packages\send2trash\plat_win.py", line 86, in send2trash
<class 'OSError'>: [WinError 124] None: 'C:\\Users\\jadfajf\\AppData\\Roaming\\Anki2\\addons21\\112897~1'

**Comment by luoliyan** [comment]
That would be #46, which as far as I could tell was an invalid path error. What's the actual full path to the `1128979221` folder?

**Comment by onaphta** [comment]
Hi, the full path is C:\Users\jadfajf\AppData\Roaming\Anki2\addons21\1128979221
The problem is that if I install the files manually, the add-on will not work at all

**Comment by onaphta** [comment]
And then, if I remove the add-on, restart Anki, reinstall it from Anki, I get no installation error, but then when I restart Anki again, I get this error message:
![imagen](https://user-images.githubusercontent.com/46018074/63033349-0fe80780-beea-11e9-9666-051966ddfa31.png)

**Comment by luoliyan** [comment]
This is so frustrating. I thought I checked that the `typing` module was bundled with Anki.

Give me 10 minutes while I fix the error in the screenshot.

**Comment by onaphta** [comment]
辛苦你了！

**Comment by luoliyan** [comment]
Okay, I've been through half a dozen rounds of bug fixing today, so that will have to be enough.

Delete the `1128979221` folder completely, install v0.11.5 that was just uploaded to AnkiWeb, and good luck.

**Comment by onaphta** [comment]
It worked, thanks!
