### ISSUE TITLE
Characters with odd alternates have incorrect Pinyin tones / transcriptions

### ISSUE THREAD

**Issue by infernalis** [luoliyan/chinese-support-redux#9]
Synopsis
Characters with rare or infrequent alternates will use these for the pinyin and transcriptions.

**Steps to reproduce**
Put 草  in the field "Hanzi"
Press TAB
**Observed behavior**
The pinyin is filled with cao4
The meaning lists all of the definitions
**Expected behavior**
The pinyin is cao3. 

If you check the dictionary, it lists cao3 as the more common pronounciation:
https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb=%E8%8D%89

I noticed the unihan dictionary has a field kFrequency mentioned in the comments. Is it as simple as changing the query to order results by this field?

**Comment by infernalis** [comment]
I did a little digging and found that the database columns listed at the top of the dictdb.py file are a little misleading, for example kFrequency is missing. I've worked out that a solution to my problem is to have _get_word_pinyin in the dictdb.py class first look for characters whose english definitions don't have the word 'variant' in them, and then if it finds nothing in the first pass re-run the function allowing variants. 

This produces much more accurate pinyin for words with variants, but doesn't solve the 'multiple pronunciations issue. It's also very english-centric, although I'm not sure how to find what language is currently selected yet.

If I cleaned up the solution and made it language independent would you accept the pull request?

**Comment by luoliyan** [comment]
Sorry for dropping off the radar for so long. Thanks for the pull request.

Feel free to open an issue for any more stuff like this.

**Comment by rpetersnil** [comment]
I am still seeing this issue, on the released binary in Anki (latest update - 2019.01.17?). Specifically I am seeing it with the characters 什 （shi2 instead of shen2) and 誰（shui2 instead of shei2). Let me know if you need more info.
