### ISSUE TITLE
"Meaning" dissappeared

### ISSUE THREAD

**Issue by lollylan** [luoliyan/chinese-support-redux#91]
The translation unfortunately does no longer automatically add a translation to the card (the rest works fine), also the menu where you chose your target language is gone.

**Comment by luoliyan** [comment]
Rename your field "English" or any of the valid field names listed here: https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json

If that doesn't help, let me know.

**Comment by lollylan** [comment]
Perfect, now it works again! Thank you so much! You rock!
