### ISSUE TITLE
Meaning auto-filled doesn't work

### ISSUE THREAD

**Issue by raisx13** [luoliyan/chinese-support-redux#99]
Describe the bug
"meaning" field not auto-filling for Chinese (Basic) note type. (Sound, pinyin, etc all auto-filling)

Expected behavior
Meaning field should auto-fill (it did before I updated to most recent Anki and had to redownload this add-on). There should be "Dictionary" where to choose the language of the translation.

I have tried to change my configuration adding the fields you said according to the previous answers but it doesn't work either way. Can you be more specific about how to solve this problem?
Specs:
Windows 10 pro
Anki Version 2.1.15
Chinese Support Version Redux 0.11.5

**Comment by luoliyan** [comment]
As mentioned in the readme, the list of valid field names can be found here: https://github.com/luoliyan/chinese-support-redux/blob/master/chinese/config.json

Try renaming your "Meaning" field to "English".
